### ISSUE TITLE
Exporting x3d

### ISSUE THREAD

**Issue by ddavidebor** [usnistgov/SFA#1]
Dear Mr. Robert Lipman,

I have been looking for a long time for a software to export x3d from STEP.

II would like to kindly suggest you consider for the future, if time and resources are available, to improve the command line version of the software in a way that allows running on a unix system headless (no guy, no windows etc etc)

This would allow a great deal of companies to move the 3D visualization of step files more towards the web.

Regards,
David

**Comment by robert-lipman** [comment]
David, the conversion of STEP to X3D is based on pythonOCC which is based on Open Cascade.  I'm not sure if either can be compiled for Unix.  

This online viewer https://www.emachineshop.com/free-online-step-file-viewer/ is actually the STEP File Analyzer and Viewer software adapted to run in a web browser.  You can run it from any operating systems as long as the web browser supports x3dom.  I don't have access to other non-Windows computers so I'm not sure if it works with Unix or MacOS.

Regards,

Bob

**Comment by ddavidebor** [comment]
Thank you so much for your time and kind suggestions
