### ISSUE TITLE
STEP viewer's X3D canvas vanish on Chrome when zoom level is on/lower than 33%

### ISSUE THREAD

**Issue by billy1624** [usnistgov/SFA#3]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/30400950/155165067-eb80b813-9bbd-4701-b429-1e3cc0899496.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/30400950/155165243-15c3b211-374a-4176-9d46-6ad57d063abb.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/30400950/155165333-608bf178-a9a7-47f6-90f5-876c28197a54.png">

Thanks!! :)

**Comment by robert-lipman** [comment]
Interesting behavior.  This isn't an issue with Chrome on Windows.  It can reduce to 25% without any problems.

**Comment by billy1624** [comment]
Hey @robert-lipman, thanks for the prompt reply. I wonder what is the aspect ratio and pixel size of your Chrome window?

**Comment by billy1624** [comment]
Also, can you try zoom out to < 33%. Then, refresh the page? The vanish problem happen only when you set the zoom level then refresh the page.

**Comment by billy1624** [comment]
Ping @robert-lipman :P

**Comment by robert-lipman** [comment]
Why is the zoom level a concern for you?

**Comment by billy1624** [comment]
The zoom level is set per domain, this is true at least for Chrome. The STEP viewer is serve under the same domain of a specific web system. User of the system is usually zoomed out when using it. Hence, viewing the STEP viewer result in vanishing STEP viewer.
