### ISSUE TITLE
Build SFA for linux

### ISSUE THREAD

**Issue by Spoutnik97** [usnistgov/SFA#5]
Hi,
Is there a way to build SFA for Linux ? 

If no, is there an alternative to check the validity of a STEP file ?

**Comment by robert-lipman** [comment]
The issue is not building SFA for Linux.  SFA is dependent on a toolkit that only runs on Windows.

The Open STEP Viewer runs on Linux and has model validation.  I have not tested it.  https://openstepviewer.com/  CAD Assistant also runs on Linux https://www.opencascade.com/products/cad-assistant/
